from selenium.webdriver.common.by import By
from time import sleep

def element_capture(driver):

    alertas = driver.find_element(By.XPATH,'//*[@id="__tile_0__"]')
    checkout_vs_pedidos = driver.find_element(By.XPATH,'//*[@id="__tile_1__"]')
    media_pedidos_7d = driver.find_element(By.XPATH,'//*[@id="__tile_2__"]')
    percentual_checkout_pedidos = driver.find_element(By.XPATH,'//*[@id="__tile_3__"]')
    taxa_ecommerce = driver.find_element(By.XPATH,'//*[@id="__tile_4__"]')
    falha_na_finalizacao_pedido = driver.find_element(By.XPATH,'//*[@id="__tile_5__"]')
    microsservicos_acima_5_erro = driver.find_element(By.XPATH,'//*[@id="__tile_6__"]')
    media_acessos_7d = driver.find_element(By.XPATH,'//*[@id="__tile_7__"]')
    qtd_requicoes_sse = driver.find_element(By.XPATH,'//*[@id="__tile_8__"]')
    container_parado = driver.find_element(By.XPATH,'//*[@id="__tile_9__"]')
    container_reiniciado_recentemente = driver.find_element(By.XPATH,'//*[@id="__tile_10__"]')
    container_execucao = driver.find_element(By.XPATH,'//*[@id="__tile_11__"]')
    memoria = driver.find_element(By.XPATH,'//*[@id="__tile_12__"]')
    disco = driver.find_element(By.XPATH,'//*[@id="__tile_13__"]')
    cpu = driver.find_element(By.XPATH,'//*[@id="__tile_14__"]')
    network = driver.find_element(By.XPATH,'//*[@id="__tile_15__"]')

    sleep(2)
    take_screenshot(alertas,'alertas.png')
    sleep(2)
    take_screenshot(checkout_vs_pedidos,'checkout_vs_pedidos.png')
    sleep(2)
    take_screenshot(media_pedidos_7d,'media_pedidos_7d.png')
    sleep(2)
    take_screenshot(percentual_checkout_pedidos,'percentual_checkout_pedidos.png')
    sleep(2)
    take_screenshot(taxa_ecommerce,'taxa_ecommerce.png')
    sleep(2)
    take_screenshot(falha_na_finalizacao_pedido,'falha_na_finalizacao_pedido.png')
    sleep(2)
    take_screenshot(microsservicos_acima_5_erro,'microsservicos_acima_5_erro.png')
    sleep(2)
    take_screenshot(media_acessos_7d,'media_acessos_7d.png')
    sleep(2)
    take_screenshot(qtd_requicoes_sse,'qtd_requicoes_sse.png')
    sleep(2)
    take_screenshot(container_parado,'container_parado.png')
    sleep(2)
    take_screenshot(container_reiniciado_recentemente,'container_reiniciado_recentemente.png')
    sleep(2)
    take_screenshot(container_execucao,'container_execucao.png')
    sleep(2)
    take_screenshot(memoria,'memoria.png')
    sleep(2)
    take_screenshot(disco,'disco.png')
    sleep(2)
    take_screenshot(cpu,'cpu.png')
    sleep(2)
    take_screenshot(network,'network.png')

def take_screenshot(element,name):
    element.screenshot(f'images/{name}')
